#!/bin/bash

EXCLUDE_FILES=(README.md install ensure-manifest)

# Joins excluded files with |
SAVE_IFS=$IFS
IFS="|"
EXCLUDE_FILES="${EXCLUDE_FILES[*]}"
IFS=$SAVE_IFS

FILES=$(git ls-files | sed -E s/$EXCLUDE_FILES//)
for FILE in $FILES; do
  ln -sf "$PWD/$FILE" "$HOME/.$FILE"
done

ln -sf "$PWD/ensure-manifest" "$HOME/.ensure/manifest"

echo "Done"
